logging:
  level:
    root: info
    com.batch.sample: debug

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group: item
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  batch:
    job:
      names: ${job.name:NONE}
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://batchdb.csgf2dhd555j.ap-northeast-2.rds.amazonaws.com:3306/batchdb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: airi
    password: ${batchpw}
