logging:
  level:
    root: info
    com.batch.sample: debug

spring:
  batch:
    job:
      names: ${job.name:NONE}
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://batchdb.csgf2dhd555j.ap-northeast-2.rds.amazonaws.com:3306/batchdb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: airi
    password: ${batchpw}
